services:
  # Ford Risk Score Engine - Standalone Service
  - type: web
    name: yomuffler
    env: python
    plan: starter
    buildCommand: pip install -r requirements-render.txt
    startCommand: python start_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production 