services:
  # Ford Risk Score Engine - Academic Cohort System
  - type: web
    name: yomuffler
    env: python
    plan: starter
    buildCommand: pip install -r requirements-render.txt && echo "FORCING INTERACTIVE VERSION BUILD $(date)"
    startCommand: python simple_production.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production 
      - key: HOST
        value: 0.0.0.0 